### ISSUE TITLE
ValueError: Model filename not in model list: ggml-gpt4all-j-v1.3-groovy.bin

### ISSUE THREAD

**Issue by fogs** [localagi/gpt4all-docker#2]
When running ```docker run localagi/gpt4all-cli:main repl``` I am getting this error:

```
Traceback (most recent call last):

  File "/cli/app.py", line 118, in <module>
    app()

  File "/cli/app.py", line 56, in repl
    gpt4all_instance = GPT4All(model)

  File "/gpt4all/gpt4all-bindings/python/gpt4all/gpt4all.py", line 48, in __init__
    model_dest = self.retrieve_model(model_name, model_path=model_path, allow_download=allow_download)

  File "/gpt4all/gpt4all-bindings/python/gpt4all/gpt4all.py", line 109, in retrieve_model
    raise ValueError(f"Model filename not in model list: {model_filename}")

ValueError: Model filename not in model list: ggml-gpt4all-j-v1.3-groovy.bin
```

The docs should give more context than just ```docker run localagi/gpt4all-cli:main --help``` - consider linking to what you could / should do next after installing the docker image.

**Comment by Zibri** [comment]
same here
